apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: telegraf:1.30
        env:
        - name: INFLUXDB_V2_TOKEN
          value: "qp7BoN2JdcCWkb5UQPcnlYNO7HW5gXIxichHRNH49gg7gq8vs0QD1lGU80wfQyAIwROxtUjcJLxj0xGRaWgrDA=="
        command: [ "telegraf" ]
        args: [ "--watch-config", "poll" ]
        ports:
        - containerPort: 8125
          protocol: TCP
        volumeMounts:
        - name: telegraf-config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
        - name: docker-sock
          mountPath: /var/run/docker.sock
          readOnly: true
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket

